# Generated by Django 5.0.6 on 2024-09-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_wish_wishitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='wish_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='quantity',
        ),
    ]
